/*

- Things Sridhar mentioned would be on the quiz or exam:
	- From March 11th
		- Queues
			- How to tell if a queue is full
			- Probably want to know class definition for array and LinkedList implementations
		- Radix Sort ** mentioned it's one of his favorite questions **
			- Queue implentation
			- Know the algorithm
	- From March 13th
		- Maximum number of non-empty nodes in a binary tree of height h
		- Definition of a full binary tree
		- Minimum height of a binary tree with n number of nodes
	- From March 25th
		- Recursive algorithms for pre order, in order, post order traversals
		- Non-recursive algorithms for pre order, in order traversals
	- From March 27th
		- Number of ways to store a binary tree
	- From April 1st // exam, not quiz
		- Self Adjusting Binary Search Trees
		- Zig and Zag operations
		- Given a BST, do a splay on a given node
		- Given a splay tree, find a given node

- Things we went over but were not said would be on quiz or exam:
	- From March 11th
		- Simple bucket sort
			- Complexity 
			- Problems
		- Radix sort
			- Complexity
			- The one problem
	- From March 13th
		- Operations
	- From March 25th
		- Project 4 information
	- From March 27th
		- Binary Search Tree
	- From April 1st
		- Finding values in BST
		- Removing values in BST
		- BST complexity
*/